# This is a basic workflow to help you get started with Actions

name: "Newman Tests"
# on: [push, pull_request]
on:
  push:
    branches:
    - anshu6

jobs:
  build:
    runs-on: ubuntu-latest
    container: 
     image: postman/newman
    steps:
     - name: Checkout
       uses: actions/checkout@v3
       with:
        # Repository name with owner. For example, actions/checkout
        # Default: ${{ github.repository }}
        ref: 'anshu2'
        
     - name: Run API Tests
       run: newman run ./Automation/Postman/collections/UserCheckoutFlow/"User Checkout Flow.postman_collection.json" -e ./Automation/Postman/envs/DevQA.postman_environment.json -d ./Automation/Postman/collections/UserCheckoutFlow/DataFiles/DevQA_UserCheckoutFlow.json
        
      
    #steps:
    #- name: Echo test
     # run: echo "I Echoed successfully"
