# This is a basic workflow to help you get started with Actions

name: "Newman Tests"
# on: [push, pull_request]
on:
  push:
    branches:
    - anshu6

jobs:
  build:
    runs-on: ubuntu-latest
    #container: 
     # image: postman/newman
    steps:
     - name: Checkout
       uses: actions/checkout@v3
       with:
        # Repository name with owner. For example, actions/checkout
        # Default: ${{ github.repository }}
        repository: 'polakala/LemonHatApp'
        ref: 'forWebUI'
        ssh-key: 'ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIMxm4V2b//pZ+MhFF/E1gd66a/2aNMLnQ+k87M1vZzP3 anshuman.manral@lemonhat.io'
        
      
    #steps:
    #- name: Echo test
     # run: echo "I Echoed successfully"
