# This is a basic workflow to help you get started with Actions

name: "Newman Tests"
# on: [push, pull_request]
on:
  push:
    branches:
    - anshu6
    - anshu4
  schedule:
    - cron: '*/15 * * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      data_file: DevQA_UserCheckoutFlow.json
    #container: 
     #image: postman/newman
    steps:
     - name: ChangeUserDataFile
       id: change_user_datafile
       if: github.event_name != 'schedule'
       env:
         data_file: DevQA_UserCheckoutFlow_scheduled.json
        
     - name: Checkout
       uses: actions/checkout@v3
       #with:
        # Repository name with owner. For example, actions/checkout
        # Default: ${{ github.repository }}
        #ref: 'anshu2'
        
     #- name: Run API Tests
       #run: newman run ./Automation/Postman/collections/UserCheckoutFlow/"User Checkout Flow.postman_collection.json" -e ./Automation/Postman/envs/DevQA.postman_environment.json -d ./Automation/Postman/collections/UserCheckoutFlow/DataFiles/DevQA_UserCheckoutFlow.json
     - name: Dump GitHub context
       id: github_context_step
       run: echo '${{ toJSON(github) }}'
       
     # Example 1
     - name: Get changed files
       id: changed-files
       uses: tj-actions/changed-files@v35

     - name: List all changed files
       run: |
          for file in ${{ steps.changed-files.outputs.all_changed_files }}; do
            echo "$file was changed"
          done
          
    # Example 2
     - name: Get changed files in the Automation folder
       id: changed-files-specific
       uses: tj-actions/changed-files@v35
       with:
        files: Automation/**  # Alternatively using: `docs/**` or `docs`

     - name: Run step if any file(s) in the Automation folder change or its a scheduled trigger
       if: steps.changed-files-specific.outputs.any_changed == 'true' || github.event_name == 'schedule'      
       run: |
          echo "One or more files in the Automation folder has changed."
          echo "List all the files that have changed: ${{ steps.changed-files-specific.outputs.all_changed_files }}"
          npm install -g newman-reporter-htmlextra
          mkdir -p testResults
          newman run ./Automation/Postman/collections/UserCheckoutFlow/"User Checkout Flow.postman_collection.json" -e ./Automation/Postman/envs/DevQA.postman_environment.json -d ./Automation/Postman/collections/UserCheckoutFlow/DataFiles/$data_file -r htmlextra --reporter-htmlextra-export testResults/htmlreport.html --reporter-htmlextra-browserTitle "LH Smoke Test Report" --reporter-htmlextra-title "LH Smoke Dashboard"
          
     - name: Output the run Details
       if: steps.changed-files-specific.outputs.any_changed == 'true' || github.event_name == 'schedule'
       uses: actions/upload-artifact@v2
       with: 
          name: RunReports
          path: testResults
      
    #steps:
    #- name: Echo test
     # run: echo "I Echoed successfully"
