# This is a basic workflow to help you get started with Actions

name: "Newman Tests"
# on: [push, pull_request]
on:
  push:
    branches:
    - anshu6

jobs:
  build:
    runs-on: ubuntu-latest
    #container: 
     # image: postman/newman
    steps:
     - name: Checkout
       uses: actions/checkout@v3
       with:
        # Repository name with owner. For example, actions/checkout
        # Default: ${{ github.repository }}
        repository: 'polakala/LemonHatApp'
        ref: 'forWebUI'
        ssh-key: 'b3BlbnNzaC1rZXktdjEAAAAABG5vbmUAAAAEbm9uZQAAAAAAAAABAAAAMwAAAAtzc2gtZWQyNTUxOQAAACDMZuFdm//6WfjIRRfxNYHeumv9mjTC50PpPOzNb2cz9wAAAKD/osra/6LK2gAAAAtzc2gtZWQyNTUxOQAAACDMZuFdm//6WfjIRRfxNYHeumv9mjTC50PpPOzNb2cz9wAAAECtcbvOAscXp3lbXhiEdJS+lF/9jWQuBwfstnFI6Pwje8xm4V2b//pZ+MhFF/E1gd66a/2aNMLnQ+k87M1vZzP3AAAAG2Fuc2h1bWFuLm1hbnJhbEBsZW1vbmhhdC5pbwEC'
        token: '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'
        
      
    #steps:
    #- name: Echo test
     # run: echo "I Echoed successfully"
