# This is a basic workflow to help you get started with Actions

name: "Newman Tests"
# on: [push, pull_request]
on:
  push:
    branches:
    - anshu6

jobs:
  build:
    runs-on: ubuntu-latest
    #container: 
     # image: postman/newman
    steps:
     - name: Checkout
       uses: actions/checkout@v2
      
    #steps:
    #- name: Echo test
     # run: echo "I Echoed successfully"
